// src/translations/en_services.js
const en_products = {
  title: "Technologies that power my services",
  description: "Leading industry platforms, applied with precision for exceptional results",
  text: [
    "Windows",
    "Ubuntu Linux",
    "Debian Linux",
    "Rocky Linux",
    "Oracle Linux",
    "Zimbra",
    "Proxmox VE",
    "VMware",
    "Hyper-V",
    "Docker",
    "Kubernetes",
    "Amazon AWS",
    "Azure",
    "Fortinet",
    "Sophos",
    "WatchGuard",
    "Mikrotik",
    "Cisco",
    "Meraki",
    "PfSense",
    "OPNsense",
    "Ubiquiti",
    "HP",
    "Huawei",
    "TP-Link",
    "O365",
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "MySQL",
    "PostgreSQL",
    "WordPress",
    "GLPI",
    "Odoo",
    "Kali",
    "Nmap",
    "Burp Suite",
    "OpenVAS",
    "Snort",
    "Veeam",
    "Nakivo",
    "Issabela",
    "FreePBX",
    "Hikvision",
    "Dahua",
  ],
};

export default en_products;
